# Generated by Django 3.2.13 on 2022-07-13 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation_app', '0003_auto_20220704_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='required_blood_group',
            field=models.CharField(choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('N', 'Not Known')], default='N', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('N', 'Not Known')], default='N', max_length=5),
        ),
        migrations.AlterField(
            model_name='userdisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_diseases', to='blood_donation_app.disease'),
        ),
        migrations.AlterField(
            model_name='userdisease',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to=settings.AUTH_USER_MODEL),
        ),
    ]
